#!/usr/bin/python3
#-*- coding: utf-8 -*-

import sys
import getopt
import os


#PATH
path = os.getcwd()
cache = (path+'/cache')
spring = (path+'/scripts/poc/Spring')
win = (path+'/scripts/poc/Windows')
smb = (path+'/scripts/poc/Smb')
xenmobile= (path + '/scripts/poc/XenMobile')
struts2= (path + '/scripts/poc/Struts2')

opts,args = getopt.getopt(sys.argv[1:],'-h-w-v-t:-s-anon-c',['help','version','target','scan','showpoc','clean','spring','windows','smb','xenmobile'])
for opt_name,opt_value in opts:

  if opt_name in ('-h','--help'):
    print(" [+] Usage: python3 pwnserver.py [options]\n")
    print(" [+] Options:")
    print("\t  -h,--help            Show  help message")
    print("\t  -v,--version         Show program's version number")
    print("\t  -t,--target          Set scan target")
    print("\t  -w                   Output test results")
    print("\t  -s,--scan            Execution scanner")
    print("\t  --showpoc            Show all available POC")
    print("\t  -c,--clean           Clean up the cache files generated by the program")

    exit()

  if opt_name == '-w':
    print("save")
    exit()

  if opt_name in ('-v','--version'):

    print(' [+] version:1.0.1')
    exit()

  if opt_name in ('-t','--target'):
       target = (sys.argv[2])
       with open(cache+'/url.cache', 'w') as f:
          f.write(target)
       print("[+]",target)
       exit()

  if opt_name in ('-s','--scan'):
       from plugins import scan
       exit()

  if opt_name in ('-sp','--showpoc'):
       from lib.utils import showpoc
       exit()

  if opt_name in ('-c','--clean'):
       print(" [+] The cache file has been cleaned up.")
       os.system("rm -rf *.log && rm -rf cache/*")
       exit()

  if opt_name in ('--spring'):
       print("\033[1;35m [+] Vulnerability scan of Spring service\033[0m")
       os.system("python3 %s/POC_batch_process.py"%(spring))

  if opt_name in ('--windows'):
       print("\033[1;35m [+] Vulnerability scan of Windows\033[0m")
       os.system("python3 %s/POC_batch_process.py"%(win))

  if opt_name in ('--smb'):
       print("\033[1;35m [+] Vulnerability scan of SMB\033[0m")
       os.system("python3 %s/POC_batch_process.py"%(smb))

  if opt_name in ('--xenmobile'):
       print("\033[1;35m [+] Vulnerability scan of XenMobile\033[0m")
       os.system("python3 %s/POC_batch_process.py"%(xenmobile))

  if opt_name in ('--struts2'):
       print("\033[1;35m [+] Vulnerability scan of Struts2\033[0m")
       os.system("python3 %s/POC_batch_process.py"%(struts2))

  if opt_name in ('-anon'):
       print("Program under development...")
       exit()
