#!/usr/bin/bash
SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)


#POC call command
#Such as:
#python3 $SHELL_FOLDER/cve-2019-0193_cmd.py <url>:<port> 
#python3 $SHELL_FOLDER/cve-2019-17558_cmd.py <url>:<port>

